version: '3'
services:
  mysql-vnrailway-db:
    image: vn-railway-db
    restart: allways
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: viet_nam_railway
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
    ports:
      - '3306:3306'
    volumes:
      - /var/www/database/vn-railway-db:/var/lib/mysql
  vn-railway:
    container_name: vn-railway-server
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    image: vn-railway:latest
    depends_on:
      - mysql-vnrailway-db
    ports:
      - '8080:8080'
    env_file:
    - .env